services:
  db:
    image: postgres:15
    restart: always
    container_name: federal-hansard-db
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: prisma_db
    ports:
      - "5432:5432"
    volumes:
      - hansard_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma_user -d prisma_db"]
      interval: 5s
      timeout: 2s
      retries: 20

  db_manager:
    build: .
    environment:
      DATABASE_URL: postgresql://prisma_user:prisma_password@db:5432/prisma_db?schema=public
      PGUSER: prisma_user
      PGPASSWORD: prisma_password
      PGDB: prisma_db
    entrypoint: psql
    command: -U prisma_user -d prisma_db -h db -p 5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ${SYS_DIR}/client.json
        target: /root/client.json
    profiles:
      - db-tools

  update:
    extends:
      service: db_manager

    entrypoint: python3
    command: scripts/update.py

  upload:
    extends:
      service: db_manager
    entrypoint: python3
    command: scripts/upload.py

  studio:
    extends:
      service: db_manager
    entrypoint:
      - prisma
    command:
      - studio
      - --port
      - "5555"
    ports:
      - "5555:5555"

  download:
    extends:
      service: db_manager
    entrypoint: python3
    command: scripts/download.py

  reparse:
    extends:
      service: db_manager
    entrypoint: python3
    command: scripts/update.py --reparse

volumes:
  hansard_db_data:
    external: true
