version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: prisma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  db_manager:
    build: .
    environment:
      - DATABASE_URL=postgresql://prisma_user:prisma_password@db:5432/prisma_db?schema=public
    depends_on:
      - db
    volumes:
      - cache_data:/tmp
      - type: bind
        source: ${SYS_DIR}/client.json
        target: /root/client.json
    profiles:
      - db-tools

  update:
    extends:
      service: db_manager
    command: scripts/update.py

  upload:
    extends:
      service: db_manager
    command: scripts/upload.py

  studio:
    extends:
      service: db_manager
    entrypoint: prisma
    command: studio
    ports:
      - "5555:5555"

  download:
    extends:
      service: db_manager
    command: scripts/download.py

  reparse:
    extends:
      service: db_manager
    command: scripts/update.py --reparse

volumes:
  postgres_data:
  cache_data:
